import { MessagingChannel, type PrismaClient } from '@prisma/client';
import type { MessagingProvider } from './messaging-types.js';
import { findOperationalTelegramIdentityByUserId } from './messaging-repository.js';
import { resolveOtpPolicy } from './messaging-policy.js';
export type OtpDispatchPurpose = 'ACTIVATION' | 'PASSWORD_RESET';
export type LegacyOtpProvider = { readonly name: string; sendOtp(mobile: string, code: string, purpose?: OtpDispatchPurpose): Promise<void> };
type OtpDatabase = Pick<PrismaClient, 'user' | 'companyMembership' | 'userMessagingPreference' | 'messagingSystemPolicy' | 'messagingIdentity'>;
type OtpProviders = Readonly<{ telegram: MessagingProvider; bale: MessagingProvider }>;
const otpText = (code: string, purpose?: OtpDispatchPurpose) => purpose === 'ACTIVATION' ? `🔐 کد فعال‌سازی فالوآ\n\nکد یکبارمصرف شما:\n\n${code}\n\n⏱ اعتبار کد: ۵ دقیقه\n🔒 این کد را در اختیار دیگران قرار ندهید.` : purpose === 'PASSWORD_RESET' ? `🔑 بازیابی رمز عبور فالوآ\n\nکد تأیید شما:\n\n${code}\n\n⏱ اعتبار کد: ۵ دقیقه\n🔒 این کد را در اختیار دیگران قرار ندهید.` : `کد یکبارمصرف فالوآ: ${code}\nمدت اعتبار: ۵ دقیقه`;
async function destination(db: OtpDatabase, userId: string, channel: MessagingChannel): Promise<string | null> { if (channel === MessagingChannel.TELEGRAM) { const identity = await findOperationalTelegramIdentityByUserId(db, userId, true); return identity?.telegramUserId ?? null; } const identity = await db.messagingIdentity.findUnique({ where: { userId_channel: { userId, channel } }, select: { externalUserId: true, destinationId: true, status: true, verifiedAt: true } }); return identity?.status === 'ACTIVE' && identity.verifiedAt ? identity.destinationId ?? identity.externalUserId : null; }
async function deliver(db: OtpDatabase, providers: OtpProviders, channel: MessagingChannel, mobile: string, code: string, purpose?: OtpDispatchPurpose): Promise<void> { const user = await db.user.findUnique({ where: { mobile }, select: { id: true } }); if (!user) throw new Error('otp_recipient_unavailable'); const membership = await db.companyMembership.findFirst({ where: { userId: user.id, isActive: true, company: { isActive: true } }, select: { id: true } }); if (!membership) throw new Error('otp_recipient_unavailable'); const policy = await db.messagingSystemPolicy.findUnique({ where: { channel }, select: { enabled: true, otpEnabled: true, credentialsEncrypted: true } }); if (!policy?.credentialsEncrypted || !resolveOtpPolicy({ systemEnabled: policy.enabled, systemOtpEnabled: policy.otpEnabled }).enabled) throw new Error('otp_channel_unavailable'); const recipient = await destination(db, user.id, channel); if (!recipient) throw new Error('otp_channel_unavailable'); const provider = channel === MessagingChannel.TELEGRAM ? providers.telegram : providers.bale; await provider.send({ destination: recipient, text: otpText(code, purpose), ...(channel === MessagingChannel.TELEGRAM && purpose ? { metadata: { replyMarkup: { inline_keyboard: [[{ text: '📋 کپی کد', copy_text: { text: code } }]] } } } : {}) }); }
export class SelectedChannelOtpProvider implements LegacyOtpProvider { readonly name = 'selected-channel'; constructor(private readonly db: OtpDatabase, private readonly legacyProvider: LegacyOtpProvider, private readonly providers: OtpProviders) {} async sendOtp(mobile: string, code: string, purpose?: OtpDispatchPurpose): Promise<void> { const user = await this.db.user.findUnique({ where: { mobile }, select: { id: true } }); if (!user) throw new Error('otp_recipient_unavailable'); const channel = (await this.db.userMessagingPreference.findUnique({ where: { userId: user.id }, select: { otpChannel: true } }))?.otpChannel; if (!channel) { await this.legacyProvider.sendOtp(mobile, code, purpose); return; } if (channel !== MessagingChannel.TELEGRAM && channel !== MessagingChannel.BALE) throw new Error('otp_channel_unavailable'); await deliver(this.db, this.providers, channel, mobile, code, purpose); } }
export class SystemPolicyOtpProvider implements LegacyOtpProvider { readonly name = 'system-policy'; constructor(private readonly db: OtpDatabase, private readonly providers: OtpProviders) {} async sendOtp(mobile: string, code: string, purpose?: OtpDispatchPurpose): Promise<void> { const policies = await this.db.messagingSystemPolicy.findMany({ where: { channel: { in: [MessagingChannel.TELEGRAM, MessagingChannel.BALE] }, enabled: true, otpEnabled: true }, select: { channel: true, credentialsEncrypted: true } }); const configured = policies.filter((row) => row.credentialsEncrypted); if (configured.length !== 1) throw new Error('otp_channel_unavailable'); const selected = configured[0]; if (!selected) throw new Error('otp_channel_unavailable'); await deliver(this.db, this.providers, selected.channel, mobile, code, purpose); } }
export class PolicyAwareOtpProvider implements LegacyOtpProvider { readonly name: string; constructor(private readonly db: OtpDatabase, private readonly legacyProvider: LegacyOtpProvider, private readonly systemProvider: SystemPolicyOtpProvider, private readonly selectedProvider: SelectedChannelOtpProvider) { this.name = legacyProvider.name; } async sendOtp(mobile: string, code: string, purpose?: OtpDispatchPurpose): Promise<void> { const configured = await this.db.messagingSystemPolicy.count({ where: { channel: { in: [MessagingChannel.TELEGRAM, MessagingChannel.BALE] } } }); if (configured === 0) return this.legacyProvider.sendOtp(mobile, code, purpose); const user = await this.db.user.findUnique({ where: { mobile }, select: { id: true } }); if (!user) throw new Error('otp_recipient_unavailable'); const preference = await this.db.userMessagingPreference.findUnique({ where: { userId: user.id }, select: { otpChannel: true } }); if (preference?.otpChannel) return this.selectedProvider.sendOtp(mobile, code, purpose); return this.systemProvider.sendOtp(mobile, code, purpose); } }
export function createSelectedChannelOtpProvider(db: OtpDatabase, legacyProvider: LegacyOtpProvider, providers: OtpProviders): LegacyOtpProvider { const systemProvider = new SystemPolicyOtpProvider(db, providers); const selectedProvider = new SelectedChannelOtpProvider(db, legacyProvider, providers); return new PolicyAwareOtpProvider(db, legacyProvider, systemProvider, selectedProvider); }
