import type { MessagingChannel } from '@prisma/client';
import { config } from '../../config.js';
import { decryptProviderCredentials, encryptProviderCredentials, maskSecret, type ProviderCredentials } from './provider-configuration.js';
import { findAllProviderConfigs, findProviderConfig, upsertProviderConfigs, type ProviderConfigRow, type UpsertProviderConfigInput } from './provider-config-repository.js';

export interface ProviderConfigSummary { channel: MessagingChannel; displayName: string; botUsername: string | null; credentialConfigured: boolean; botTokenMasked: string | null; enabled: boolean; notificationEnabled: boolean; otpEnabled: boolean; }
export interface RuntimeProviderConfig { channel: MessagingChannel; displayName: string; botUsername: string | null; botToken: string; enabled: boolean; notificationEnabled: boolean; otpEnabled: boolean; }
const CHANNEL_LABELS: Partial<Record<string, string>> = { TELEGRAM: 'تلگرام', BALE: 'بله' };

export async function getProviderSummaries(channels: readonly MessagingChannel[]): Promise<ProviderConfigSummary[]> { const configs = await findAllProviderConfigs(channels); return channels.map((ch) => summarize(ch, configs.get(ch))); }
export async function getProviderSummary(channel: MessagingChannel): Promise<ProviderConfigSummary> { return summarize(channel, await findProviderConfig(channel)); }
export function decryptCredentials(encrypted: string): ProviderCredentials { assertMasterKey(); return decryptProviderCredentials(encrypted, config.messagingCredentialsKey); }
export async function getRuntimeProviderConfig(channel: MessagingChannel): Promise<RuntimeProviderConfig | null> { const row = await findProviderConfig(channel); if (!row?.enabled || !row.credentialsEncrypted) return null; try { const credentials = decryptCredentials(row.credentialsEncrypted); return { channel: row.channel, displayName: row.displayName ?? CHANNEL_LABELS[channel] ?? channel, botUsername: row.botUsername, botToken: credentials.botToken, enabled: row.enabled, notificationEnabled: row.notificationEnabled, otpEnabled: row.otpEnabled }; } catch { return null; } }
export function isMasterKeyConfigured(): boolean { return config.messagingCredentialsKey.trim().length >= 32; }
export interface SaveProviderConfigInput { channel: MessagingChannel; displayName: string; botUsername: string | null; enabled: boolean; notificationEnabled: boolean; otpEnabled: boolean; botToken?: string | null; }
export async function saveProviderConfigs(inputs: SaveProviderConfigInput[]): Promise<void> { const upserts: UpsertProviderConfigInput[] = inputs.map(({ botToken, ...rest }) => { let credentialsEncrypted: string | null | undefined; if (botToken === undefined) credentialsEncrypted = undefined; else if (botToken === null) credentialsEncrypted = null; else { assertMasterKey(); credentialsEncrypted = encryptProviderCredentials({ botToken }, config.messagingCredentialsKey); } return { ...rest, credentialsEncrypted }; }); await upsertProviderConfigs(upserts); }
function assertMasterKey(): void { if (config.messagingCredentialsKey.trim().length < 32) throw new Error('messaging_credentials_key_missing_or_too_short'); }
function summarize(channel: MessagingChannel, row: ProviderConfigRow | null | undefined): ProviderConfigSummary { return { channel, displayName: row?.displayName ?? CHANNEL_LABELS[channel] ?? channel, botUsername: row?.botUsername ?? null, credentialConfigured: Boolean(row?.credentialsEncrypted), botTokenMasked: maskedToken(row?.credentialsEncrypted ?? null), enabled: row?.enabled ?? false, notificationEnabled: row?.notificationEnabled ?? false, otpEnabled: row?.otpEnabled ?? false }; }
function maskedToken(encrypted: string | null): string | null { if (!encrypted || !isMasterKeyConfigured()) return null; try { return maskSecret(decryptProviderCredentials(encrypted, config.messagingCredentialsKey).botToken); } catch { return '••••'; } }
