'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { api, clearAuth, setAuth } from '@/lib/api';
import { btnPrimary, Field, inputClass } from '@/components/ui';

type Step = 'mobile' | 'code' | 'password';

export default function OtpPage() {
  const router = useRouter(); const [step, setStep] = useState<Step>('mobile'); const [mobile, setMobile] = useState(''); const [code, setCode] = useState(''); const [resetToken, setResetToken] = useState(''); const [password, setPassword] = useState(''); const [password2, setPassword2] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const requestCode = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setLoading(true); try { await api.post('/auth/otp/request', { mobile }); setStep('code'); } catch (err) { setError(err instanceof globalThis.Error ? err.message : 'خطا'); } finally { setLoading(false); } };
  const verifyCode = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setLoading(true); try { const res = await api.post<{ resetToken: string }>('/auth/otp/verify', { mobile, code }); setResetToken(res.resetToken); setStep('password'); } catch (err) { setError(err instanceof globalThis.Error ? err.message : 'خطا'); } finally { setLoading(false); } };
  const createPassword = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (password !== password2) { setError('تکرار رمز عبور مطابقت ندارد'); return; } setLoading(true); try { await api.post('/auth/password', { mobile, resetToken, password }); const res = await api.post<{ token: string; user: unknown }>('/auth/login', { mobile, password }); clearAuth(); setAuth(res.token, res.user); router.replace('/dashboard'); } catch (err) { setError(err instanceof globalThis.Error ? err.message : 'خطا'); } finally { setLoading(false); } };
  const steps = ['mobile', 'code', 'password'] as const; const current = steps.indexOf(step);
  return <div className="flex min-h-screen items-center justify-center bg-workspace-canvas p-5"><div className="w-full max-w-[520px]"><div className="mb-7 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-brand-500 to-brand-700 text-base font-black text-white shadow-[0_12px_28px_rgba(124,77,255,.25)]">ف</span><div><p className="font-black text-white">فعال‌سازی حساب فالوآ</p><p className="mt-0.5 text-[9px] text-workspace-soft">با شماره‌ای که مدیر شرکت برای شما ثبت کرده است</p></div></div><div className="rounded-2xl border border-workspace-border bg-workspace-surface p-5 shadow-workspace sm:p-6"><ol className="mb-7 grid grid-cols-3 gap-2">{['شماره موبایل', 'کد تأیید', 'رمز عبور'].map((label, index) => <li key={label} className={`rounded-xl border p-3 ${index <= current ? 'border-brand-400/20 bg-brand-400/10' : 'border-workspace-border bg-workspace-elevated/45'}`}><span className={`tnum grid h-6 w-6 place-items-center rounded-lg text-[10px] font-black ${index <= current ? 'bg-brand-600 text-white' : 'bg-workspace-border text-workspace-soft'}`}>{(index + 1).toLocaleString('fa-IR')}</span><p className={`mt-2 text-[10px] font-semibold ${index <= current ? 'text-brand-100' : 'text-workspace-soft'}`}>{label}</p></li>)}</ol>
    {step === 'mobile' && <form onSubmit={requestCode} className="space-y-4"><Field label="شماره موبایل" required><input className={`${inputClass} tnum text-left`} dir="ltr" inputMode="numeric" placeholder="09123456789" value={mobile} onChange={(event) => setMobile(event.target.value)} autoFocus /></Field><AuthError message={error} /><button type="submit" disabled={loading} className={btnPrimary}>{loading ? 'در حال ارسال…' : 'دریافت کد تأیید'}</button></form>}
    {step === 'code' && <form onSubmit={verifyCode} className="space-y-4"><div className="rounded-xl border border-workspace-border bg-workspace-elevated/55 p-3 text-[11px] leading-6 text-workspace-muted">کد ۶ رقمی برای <span className="tnum font-bold text-white">{mobile}</span> ارسال شد.{process.env.NEXT_PUBLIC_SHOW_OTP === 'true' && <span className="block text-[9px] text-amber-300">حالت توسعه: کد در لاگ سرور نمایش داده می‌شود.</span>}</div><Field label="کد تأیید" required><input className={`${inputClass} tnum text-center text-lg tracking-[0.5em]`} dir="ltr" inputMode="numeric" maxLength={6} placeholder="——————" value={code} onChange={(event) => setCode(event.target.value)} autoFocus /></Field><AuthError message={error} /><button type="submit" disabled={loading} className={btnPrimary}>{loading ? 'در حال بررسی…' : 'تأیید کد'}</button><button type="button" onClick={() => setStep('mobile')} className="w-full text-center text-[11px] text-workspace-muted hover:text-white">تغییر شماره موبایل</button></form>}
    {step === 'password' && <form onSubmit={createPassword} className="space-y-4"><Field label="رمز عبور جدید" required><input type="password" className={inputClass} dir="ltr" value={password} onChange={(event) => setPassword(event.target.value)} autoFocus /></Field><Field label="تکرار رمز عبور" required><input type="password" className={inputClass} dir="ltr" value={password2} onChange={(event) => setPassword2(event.target.value)} /></Field><p className="text-[10px] text-workspace-soft">رمز عبور حداقل ۸ کاراکتر باشد.</p><AuthError message={error} /><button type="submit" disabled={loading} className={btnPrimary}>{loading ? 'در حال ثبت…' : 'ساخت رمز و ورود'}</button></form>}
    <p className="mt-6 border-t border-workspace-border pt-4 text-center text-[11px] text-workspace-muted">قبلاً رمز دارید؟ <Link href="/login" className="font-bold text-brand-300 hover:text-brand-200">ورود با رمز</Link></p></div></div></div>;
}
function AuthError({ message }: { message: string }) { return message ? <div className="rounded-xl border border-red-400/20 bg-red-400/10 px-3.5 py-2.5 text-xs text-red-200">{message}</div> : null; }
