'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { btnPrimary, btnSecondary, Card, EmptyState, ErrorState, Field, inputClass, Modal, Spinner, Toast } from '@/components/ui';
import { CheckIcon, ClockIcon, RemindersIcon } from '@/components/workspace/icons';
import { PageHeader } from '@/components/workspace/page';
import { faDateTime } from '@/lib/jalali';

interface ReminderRow { id: string; caseId: string; remindAt: string; note: string | null; status: string; completedAt: string | null; case: { id: string; title: string; number: number; status: string }; }

export default function RemindersPage() {
  const [items, setItems] = useState<ReminderRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [tab, setTab] = useState<'ACTIVE' | 'TODAY' | 'DONE' | 'EXPIRED'>('ACTIVE'); const [toast, setToast] = useState<{ message: string; tone: 'success' | 'error' } | null>(null); const [completing, setCompleting] = useState<ReminderRow | null>(null);
  const showToast = (message: string, tone: 'success' | 'error') => { setToast({ message, tone }); setTimeout(() => setToast(null), 3000); };
  const load = useCallback(async () => { try { setError(''); await api.get('/reminders/due-check').catch(() => {}); const res = tab === 'TODAY' ? await api.get<{ items: ReminderRow[] }>('/reminders?today=true&status=ACTIVE') : await api.get<{ items: ReminderRow[] }>(`/reminders?status=${tab}`); setItems(res.items); } catch (err) { setError(err instanceof Error ? err.message : 'خطا'); } finally { setLoading(false); } }, [tab]);
  useEffect(() => { setLoading(true); void load(); }, [load]);
  const tabs = [{ key: 'ACTIVE', label: 'فعال' }, { key: 'TODAY', label: 'امروز' }, { key: 'DONE', label: 'انجام‌شده' }, { key: 'EXPIRED', label: 'گذشته' }] as const;
  const overdueCount = items.filter((item) => item.status === 'ACTIVE' && new Date(item.remindAt) < new Date()).length;

  return <div className="space-y-5">{toast && <Toast message={toast.message} tone={toast.tone} />}<PageHeader eyebrow="پیگیری شخصی" title="یادآوری‌ها" description="موارد پیگیری را بر اساس وضعیت و زمان سررسید مرور کنید و نتیجه انجام را روی پرونده ثبت کنید." icon={<RemindersIcon className="h-5 w-5" />} meta={overdueCount > 0 ? <span className="text-red-300">{overdueCount.toLocaleString('fa-IR')} مورد از سررسید عبور کرده</span> : 'وضعیت پیگیری‌های شما'} />
    <div className="flex gap-2 overflow-x-auto rounded-2xl border border-workspace-border bg-workspace-surface p-2 shadow-card">{tabs.map((item) => <button key={item.key} onClick={() => setTab(item.key)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-xs font-semibold transition ${tab === item.key ? 'bg-brand-600 text-white shadow-[0_8px_20px_rgba(109,54,237,.18)]' : 'text-workspace-muted hover:bg-workspace-hover hover:text-white'}`}>{item.label}</button>)}</div>
    {loading ? <Spinner /> : error ? <ErrorState message={error} onRetry={load} /> : items.length === 0 ? <Card><EmptyState title="یادآوری‌ای در این بخش نیست" hint="از صفحه جزئیات هر پرونده می‌توانید یادآوری جدید بسازید." /></Card> : <div className="grid gap-3 xl:grid-cols-2">{items.map((reminder) => { const overdue = reminder.status === 'ACTIVE' && new Date(reminder.remindAt) < new Date(); const done = reminder.status === 'DONE'; return <Card key={reminder.id} className="relative overflow-hidden p-4"><span className={`absolute inset-y-4 right-0 w-0.5 rounded-full ${overdue ? 'bg-red-400' : done ? 'bg-emerald-400' : 'bg-amber-400'}`} /><div className="flex items-start gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl border ${overdue ? 'border-red-400/20 bg-red-400/10 text-red-300' : done ? 'border-emerald-400/20 bg-emerald-400/10 text-emerald-300' : 'border-amber-400/20 bg-amber-400/10 text-amber-300'}`}>{done ? <CheckIcon className="h-5 w-5" /> : <ClockIcon className="h-5 w-5" />}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-black text-workspace-ink">{reminder.note || reminder.case.title}</p><Link href={`/cases/${reminder.caseId}`} className="mt-1.5 block truncate text-[10px] font-semibold text-brand-300 hover:text-brand-200">#{reminder.case.number.toLocaleString('fa-IR')} · {reminder.case.title}</Link><p className={`tnum mt-2 text-[10px] font-semibold ${overdue ? 'text-red-300' : 'text-workspace-soft'}`}>{faDateTime(reminder.remindAt)}{overdue ? ' · سررسید گذشته' : ''}</p></div></div>{reminder.status === 'ACTIVE' && <div className="mt-4 border-t border-workspace-border pt-3"><button onClick={() => setCompleting(reminder)} className="inline-flex items-center gap-2 rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-3.5 py-2 text-[11px] font-bold text-emerald-300 transition hover:bg-emerald-400/15"><CheckIcon className="h-4 w-4" />انجام شد + ثبت نتیجه</button></div>}</Card>; })}</div>}
    <CompleteReminderModal reminder={completing} onClose={() => setCompleting(null)} onDone={() => { setCompleting(null); void load(); }} showToast={showToast} />
  </div>;
}

function CompleteReminderModal({ reminder, onClose, onDone, showToast }: { reminder: ReminderRow | null; onClose: () => void; onDone: () => void; showToast: (message: string, tone: 'success' | 'error') => void }) {
  const [result, setResult] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (reminder) setResult(reminder.note ?? ''); }, [reminder]);
  return <Modal open={Boolean(reminder)} onClose={onClose} title="ثبت نتیجه یادآوری">{reminder && <form onSubmit={async (event) => { event.preventDefault(); setBusy(true); try { await api.post(`/reminders/${reminder.id}/complete`, { result: result || undefined }); showToast('یادآوری انجام شد', 'success'); onDone(); } catch (err) { showToast(err instanceof Error ? err.message : 'خطا', 'error'); } finally { setBusy(false); } }} className="space-y-4"><div className="rounded-xl border border-workspace-border bg-workspace-elevated/55 p-3 text-[11px] leading-6 text-workspace-muted">نتیجه در تاریخچه پرونده «{reminder.case.title}» نیز ثبت می‌شود.</div><Field label="نتیجه پیگیری"><textarea className={`${inputClass} min-h-28`} value={result} onChange={(event) => setResult(event.target.value)} autoFocus placeholder="نتیجه انجام پیگیری را بنویسید…" /></Field><div className="flex gap-3"><button disabled={busy} className={btnPrimary}>{busy ? 'در حال ثبت…' : 'ثبت نتیجه و تکمیل'}</button><button type="button" onClick={onClose} className={btnSecondary}>انصراف</button></div></form>}</Modal>;
}
