import { MessagingChannel } from '@prisma/client';
import { prisma } from '../../lib/prisma.js';
import type { MessagingProvider } from '../messaging/messaging-types.js';
import { createSelectedChannelOtpProvider, SystemPolicyOtpProvider } from '../messaging/otp-dispatcher.js';
import { getDatabaseConfiguredProvider } from '../messaging/db-backed-provider.js';
import { createTelegramRepository } from '../telegram/telegram-repository.js';
export type OtpDeliveryPurpose = 'ACTIVATION' | 'PASSWORD_RESET';
export interface OtpProvider { readonly name: string; sendOtp(mobile: string, code: string, ...context: [purpose?: OtpDeliveryPurpose]): Promise<void>; }
type TelegramOtpRepository = { findUserByMobile(mobile: string): Promise<{ id: string; mobile: string } | null>; findIdentityByUserId(userId: string): Promise<{ telegramUserId: string; userId: string } | null> };
export class TelegramOtpProvider implements OtpProvider { readonly name = 'telegram'; constructor(private readonly repository: TelegramOtpRepository = createTelegramRepository(prisma), private readonly provider: MessagingProvider = getDatabaseConfiguredProvider(MessagingChannel.TELEGRAM)) {} async sendOtp(mobile: string, code: string, ...context: [purpose?: OtpDeliveryPurpose]): Promise<void> { const [purpose] = context; const user = await this.repository.findUserByMobile(mobile); if (!user) throw new Error('telegram_otp_user_not_found'); const identity = await this.repository.findIdentityByUserId(user.id); if (!identity) throw new Error('telegram_otp_identity_not_linked'); const text = purpose === 'ACTIVATION' ? `🔐 کد فعال‌سازی فالوآ\n\nکد یکبارمصرف شما:\n\n${code}\n\n⏱ اعتبار کد: ۵ دقیقه\n🔒 این کد را در اختیار دیگران قرار ندهید.` : purpose === 'PASSWORD_RESET' ? `🔑 بازیابی رمز عبور فالوآ\n\nکد تأیید شما:\n\n${code}\n\n⏱ اعتبار کد: ۵ دقیقه\n🔒 این کد را در اختیار دیگران ندهید.` : `کد یکبارمصرف فالوآ: ${code}\nمدت اعتبار: ۵ دقیقه`; await this.provider.send({ destination: identity.telegramUserId, text, ...(purpose ? { metadata: { replyMarkup: { inline_keyboard: [[{ text: '📋 کپی کد', copy_text: { text: code } }]] } } } : {}) }); } }
export function createOtpProvider(): OtpProvider { const providers = { telegram: getDatabaseConfiguredProvider(MessagingChannel.TELEGRAM), bale: getDatabaseConfiguredProvider(MessagingChannel.BALE) }; const systemProvider = new SystemPolicyOtpProvider(prisma, providers); return createSelectedChannelOtpProvider(prisma, systemProvider, providers); }
